[package]
name = "rusty_yazi"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1" # Main GUI framework
egui_extras = { version = "0.29.1", features = ["all_loaders"] } # For tables/images
chrono = "0.4"    # For file timestamps
open = "5.3"      # To open files with system default
directories = "5.0" # To find Home directory
bytesize = "1.3"  # For human readable file sizes